### ISSUE TITLE
P1 Completion 1/13 _ Add RSS Feed Tab to Landing Page

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#101]
Phase 1 Completion Requirement 1/13

In a new tab beside the Event feed tab, MSF require an RSS Feed tab which includes a table of feeds from PDC (which includes in table format more info that the geospatial display at the landing page map), as well as these other feeds:
https://earthquake.usgs.gov/earthquakes/feed/ 
http://ptwc.weather.gov/ 
http://www.tropicalstormrisk.com/
GDAX (Lucie will add website for GDAX)

<img width="1020" alt="screen shot 2017-09-03 at 9 17 32 am" src="https://user-images.githubusercontent.com/20785542/30001259-cdf1f5b6-9088-11e7-9f35-b33c836e97e7.png">

( Please note that UX improvements for this navigation bar are at the top of the list for Phase 2; however, the tab with the RSS feeds is required in this configuration for completion of Phase 1. )

**Comment by matthewberryman** [comment]
@LucieGueuning I guess @anexact means the GDACS (not GDAX) feed from http://www.gdacs.org/ ? Please confirm asap.

**Comment by anexact** [comment]
Confirm GDACS.

**Comment by matthewberryman** [comment]
Just adding a comment to track completion of individual feeds.
* ~~USGS~~
* ~~tropical storm risk~~
* PTWC
* GDACS

**Comment by matthewberryman** [comment]
@LucieGueuning This is now done, including mapping of all of the data from the extra feeds, along with the ability to click on a row in the RSS field (anywhere not on the icon) and it will take you to that event on the map. Similar to #109 and #110 functionality. To make this ability a bit clearer, in https://github.com/MSFREACH/msf-reach/issues/129 I have asked the guys to make the row darker when you mouse over it, so that it's clearer you can click on it, as well as adding mouseover and touch support for highlighting a row based on touching/mousing over an event. Most of the code I've written for that but there's a bug and I'm out of time for today on that. I've added that issue to phase 1 milestone.

There are two other cosmetic issues for phase 2, since the involve substantial amounts of work (likely several days full time each)
1. This one makes a fairly minor difference (i.e. it's still quite usable without this), but it would be nice to do https://github.com/MSFREACH/msf-reach/issues/128 - the merging we will likely have to get https://github.com/mapbox/geojson-merge working client side and make sure ordering is happening, but detecting overlap is move involved still as the data sources are quite different in format. 
2. The summary information for the PTWC feed isn't nice and concise like the other feeds. It's a long set of text, see https://github.com/MSFREACH/msf-reach/issues/127 , that I will need to
  - Chase down documentation for (going to take a day or two of searching)
  - Write a parser from scratch for (going to take several days incl. testing).

**Comment by matthewberryman** [comment]
@LucieGueuning just to be a little clearer in my previous comment, you can now click on a row in the rss feed (separate to the link that opens the rss details). It's just the ability to go in reverse (by mouseover an event on the map, to highlight a row) that needs a bug fix.

**Comment by LucieGueuning** [comment]
Have you open a new issue for this bug fix? Should we keep track on those issue for Phase by marking them as Phase 2 - milestones? #127 # 128

**Comment by matthewberryman** [comment]
@LucieGueuning Yes, opened #127, #128 and #129 (and then closed #129 as the smaller one on the path to phase 1). Let's discuss phase 2 milestones in our next skype meeting - we can go through these and assign then if need be—depends on whether we think #127 and #128 are worth doing as part of phase 2 or if we should focus on other things first, and we need to decide which part of phase 2 they fall in. If you like, assign them now before our meeting and then we can review.
