### ISSUE TITLE
P1 Completion 4/13 _ MSF Contact Details as New Window

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#104]
Phase 1 Completion Requirement 4/13

MSF requires a more complete display of Contact information; while the "Quick View" in the Table, and for the Hover/1 Click on the map are detailed in a previous issues, this requirement refers to a new window for complete contact information that would be opened from the table or the map.

ET can discuss UX options; **LG** will add the **Minimum List of Required Fields** for the Contact Details popup window in the comments to this issue below.

**Comment by LucieGueuning** [comment]
Sorry for the delay. 
Please find below the **Minimum List of Required Fields** when window open to show full information about one specific contact : 

Profile ID
Filling date
Last update
Last email sent
First Name
Last Name
Other names
Title
Type of contact
Nationality
Nationality 2
Gender
Date of birth
Email address
Email address 2
Phone number Mobile
Phone number Work
Phone number Home
Location of living (street and number + city)
Country of living
WhatsApp
Facebook
Twitter
Instagram
Telegram
Skype
Affiliation (employer) - Company Name
For MSF staff only : OC/PS-BO/Mission
Category
Current employement status
Current Position - Job title
Profile/Speciality

**Comment by matthewberryman** [comment]
Ok I think we'll struggle to fit all of those on. Perhaps for social media we can group those together, as it's doubtful someone would have all of them. We'll give this a go, but it would be useful to have them in order of priority in case we can't (also, I am assuming you want title before first name).

**Comment by LucieGueuning** [comment]
Maybe what we can do is open and show only the ones which are filled and remove the fields which are empty. Some contact don't have all information. 

- thank for your 'go'. 
- what do you mean by 'title' before first name?

**Comment by matthewberryman** [comment]
We need to have one list for all contacts; we can't chop and change fields on a per contact basis e.g. suppose one contact has an affiliation listed but another one doesn't, then we either need to display an affiliation column for all contacts and leave it blank if absent, or not have an affiliation column.

Title is "Dr", "Mr", "Mrs" etc.

**Comment by LucieGueuning** [comment]
@anexact

**Comment by matthewberryman** [comment]
@LucieGueuning just flagging that some of these, 
* Last update
* Last email sent
* MSF subdetails per dropdown #67 
(none of these flagged for phase 1) aren’t captured in contact cards.
Also profile ID (from our database-generated ID) doesn’t seem worth displaying. Please clarify what you want us to do.

**Comment by LucieGueuning** [comment]
Those information, as specified on 'specification', are auto-filled by the system to keep record how far those contact information are still up to date. Do you know what I mean?

Also, all field in detailed view are empty even if we have information on excel file.

**Comment by matthewberryman** [comment]
I’m afraid it’s not really clear. You haven’t asked us for the ability to update contact cards as part of phase 1, so we cannot display last update time (since there are no updates) nor details of last email sent to that contact.

With regards to information from the Google docs spreadsheet: I cannot check on current UX until after I return to Shanghai late tomorrow, however in general there were a lot of blanks in the provided spreadsheet (as mentioned, nothing on speciality, amongst other gaps). Can you please be more specific as to what information you think is present in the spreadsheet that should be in the detailed view that I can review on Thursday.

Sent from my iPhone

On 27 Sep 2017, at 16:43, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


Those information, as specified on 'specification', are auto-filled by the system to keep record how far those contact information are still up to date. Do you know what I mean?

Also, all field in detailed view are empty even if we have information on excel file.

**Comment by LucieGueuning** [comment]
1. Agreed, we still do not have those information but we will need to put it on at some point. So solution would be to put there without information. This way, people can know that this kind of information will be filled out when we receive this information. 

2. for example, 'Christina Geros' on spreadsheet fill out all information. But on REACH, she has only 4 information (the ones in quick view) which are completed (name;affiliation;phone and email).

**Comment by matthewberryman** [comment]
@LucieGueuning 
1. Ok I have added some fields in (deploying now, but let me double check first) on top of @rcdelfin's work on the rest. Some of the data in the fields (filed time, and MSF details) isn't captured in contact cards (on this platform) but was in spreadsheet (see note 2) so that should show up for those entries from the spreadsheet.
2. Some of the data wasn't coming through because I needed to update the import script in this issue https://github.com/MSFREACH/msf-reach-schema/issues/9 —when I first wrote this we didn't have the full set of fields fleshed out, but now I have updated this and also then updated the data in the database using this script.

**Comment by matthewberryman** [comment]
@LucieGueuning I think we're done with exception of other names (really required? please confirm) as we're running low on space to display. Noting #67 (phase 2? it's getting *very* late to be adding stuff to the milestone) and #124 (phase 2), though we have address data from spreadsheet in. Closing this display issue.

**Comment by LucieGueuning** [comment]
@matthewberryman 
other names : not really required. 

this is perfect except '**MSF details**' : should be only for 'MSF staff' when person checked this specific box and not for everybody (such as Christina). #67 

Also, quick view for contact needs to have the following 5 fields on table : Name / Email / Phone / Type / Affiliation (column L on spreadsheets) / Specialty #102 

Just check out what was the issue with this and comments to avoid misunderstandings. Is it clear, now?

**Comment by matthewberryman** [comment]
@LucieGueuning I have addressed the clarified requirement for #102 in an update for that issue (please try and keep comments specific to the issue they're for). I will work on making MSF details dynamic, but just flagging that this was entered as free text in the spreadsheet so I will put in some code to try and catch most of those, along with new contacts entered via our contacts form, but cannot guarantee I will catch all cases.
