### ISSUE TITLE
Contact cards - Phone and email as validated fields

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#229]
Phone fields are required. They need to accept only number as response. 
Same for email field, need to accept only valid email address. 

@talltom 

It become quiet urgent as I would like people to start fill out their contact details through the final layout of those contact cards. Thanks!

**Comment by matthewberryman** [comment]
I’ll add email formatting validation in later today. It won’t check that the domain is valid—as we cannot look this up in JavaScript in browser; we could add an API call for doing that but it would be an open API and could be abused, so I will leave that off.

Phone number validation is very hard due to formatting and other issues to do with country (each county defines what a valid number is) so I will use one of the plugins like https://github.com/jackocnr/intl-tel-input for that.



Sent from my iPhone

On 25 Jan 2018, at 04:11, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


Phone fields are required. They need to accept only number as response.
Same for email field, need to accept only valid email address.

@talltom<https://github.com/talltom>

It become quiet urgent as I would like people to start fill out their contact details through the final layout of those contact cards. Thanks!

**Comment by matthewberryman** [comment]
https://github.com/AcrossTheCloud/Mail-RFC822-Address will now generate a mammoth regex (6551 characters!) for use for email validation.

**Comment by matthewberryman** [comment]
I have tested these changes locally and it works. Just deploying to our dev environment now and will check myself after dinner.

**Comment by matthewberryman** [comment]
Not deployed yet due to #232  - will fix that now

**Comment by matthewberryman** [comment]
Fixed #232 and this new code is now deployed to dev and I did some additional testing there and seems good to me.

**Comment by LucieGueuning** [comment]
Good to me as well! Congrats. Thanks @matthewberryman
