### ISSUE TITLE
external parties to log in into REACH 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#279]
Set up right and permissions to not see confidential info form MSF for external parties (such as health sites who have requested access). 

Request approval from sponsors. 

Linked to #57

**Comment by matthewberryman** [comment]
@LucieGueuning what's the purpose of this? It's not really clear, i.e. If there's no need to see any confidential info then it's equivalent to our test environment (blank database but still with RSS feeds, public data etc.) so does that mean this is more of a test environment (with separate Active Directory, and we could make those logins self-managed by users), for them to evaluate REACH? Otherwise if we want to have fine-grained sharing of events etc. to external parties it's major work and that cannot be done without granting some level of MSF AD access.

**Comment by LucieGueuning** [comment]
Yes, you are right. So if external parties would like to see our platform without confidential info, I can give them access to the test environment? How can they log in? need to set by themselves an username and password for REACH? How can this work?

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/42683932-a08af15a-8686-11e8-8632-b65974dfb4ac.png)

**Comment by matthewberryman** [comment]
@LucieGueuning Because of the way the software has evolved based on issues raised before and after this one around functionality linked to AD it's now very hard (at least a month's full time work) to get this working. One possible approach is to think about a separate AD pool (like the testing one but one that you & the team can subscribe people too, and with a domain name that doesn't have 'test') in it.

**Comment by LucieGueuning** [comment]
as viewers into MSF address book or as operator through externs into the group
