### ISSUE TITLE
VERY IMPORTANT - events creation

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#30]
Natural disaster (earthquake/volcano/typhon/flood/tsunami/drought/others) / Armed Conflict / Disease outbreak (Cholera/Ebola/Dengue/Malaria/Measles/Meningococcal Meningitis/Yellow Fever/others) / Displacement / Malnutrition / Search and Rescue / others + specify

cc @LucieGueuning

**Comment by matthewberryman** [comment]
@mehrdadgit please work on further event fields as per events tab in https://docs.google.com/spreadsheets/d/1fGuGeet2TKD6Pxy8xm1jHEn1ujxZMWPIqeIUSV7VmCQ/edit#gid=203260487

**Comment by matthewberryman** [comment]
@mehrdadgit please double check - there are some missing, also on event archive please add a popup form for capturing ones flagged as "On closure Event ID"

**Comment by matthewberryman** [comment]
You can use the country picker (see contact card for example) to select visa countries. Need donors on initial entry, final budget on archiving, a few others missing.

**Comment by LucieGueuning** [comment]
Could you please also categorize them thanks to different tabs. You can find the categories on first column on spreadsheet.

**Comment by anexact** [comment]
UPDATE: Please note the following requested changes for EVENT CREATION—please use _only_ these fields for Operator to fill in (note, order is alphabetical, not random, for all but Status, which is sequential to deployment logic):

## First tab: BASIC INFORMATION

**Type**: choose via check box from following list: Armed Conflict; Disease Outbreak; Displacement; Malnutrition; Natural Disaster; Search & Rescue; Other (Specify)

> _IF_ Operator selects Other: Open free text box;

> _IF_ Operator selects Natural Disaster: choose from subsequent dropdown one of the following: Drought; Earthquake; Flood; Tsunami; Typhoon; Volcano; Other (Specify)
>> _IF_ Operator selects Other: Open free text box;

> _IF_ Operator selects Disease Outbreak: choose from subsequent dropdown one of the following: Cholera; Dengue; Ebola; Malaria; Measles; Meningitis; Yellow Fever; Other (Specify)
>> _IF_ Operator selects Other: Open free text box;

**Location**: Map-driven selection _OR_ Text box search using Google Address Verification Match 

**Date & Time of Event**: Calendar / Clock / Select time zone 

**Status**: select from Dropdown menu: Monitoring; Exploration; Intervention; Completed Mission

> IF Operator selects Completed Mission, prompt pop up window Are you sure? re: Archive Mission button.

**Person in Charge**: two text box fields: 
/ Name
/ Position
[MSF note to Phase 2: if we use Federation Services solution for Active Directory Authentication for MSF REACH, can this auto-populate with directory names, and then add full contact card if it is found in the Directory?]

**Severity**: free text box

**Security Information**: free text box

**Link to Sharepoint Folder**: Operation will paste Sharepoint Link here in a free text box

CREATE (button)

Once pressed, the Create button generates the event; including meta-data generated by pressing Create Event Button:
**Event Name**: Automatic via Type + Location + Time
**Time**: (of Report) : Auto-filled to time of create button.

NOTE: all fields would be "edit-able" in new event window, including the event name itself. This is because they auto-generated event name is very useful for a generic event, but for a meteorological event, like a Hurricane, will have a name (like Haiyan). Therefore, the request is that the Unique Event ID, and the Request Card connected to that Unique Event ID, would NOT be connected to the same of the event itself.  

## Additional tabs: FUTURE TABS ... future development for additional tabs for Operators re: specific event components will be added in a new ticket and can be added in Phase 2.

**Comment by LucieGueuning** [comment]
To update: 
- Event type: (do not forget the capital letter and follow the exact spelling and order: Armed Conflict; Disease Outbreak; Displacement; Malnutrition; Natural Disaster; Search & Rescue; Other (Specify)
- If natural disaster (do not forget the capital letter and follow the exact spelling and order: Drought; Earthquake; Flood; Tsunami; Typhoon; Volcano; **O**ther (Specify).
- If disease outbreak, please put capital letter for 'Other'
- time of event not possible to input. Need to be feasible to input a precise hours and minutes (not mandatory).
- for status, please follow the right spelling (also considering the capital letter): Monitoring; Exploration; Intervention; Completed Mission
- link to SharePoint Folder, needs to be the last one (as per requested on comment up). Also update the capital letter.

**Comment by matthewberryman** [comment]
@LucieGueuning just flagging that there are a couple of options for time input, one with selectors:
<img width="244" alt="screenshot 2018-03-02 13 01 46" src="https://user-images.githubusercontent.com/2288238/36879909-14fab1ae-1e1a-11e8-8794-5c8232e5599f.png">
Or the sliders that I went with as the selector lists can be unwieldy, especially on mobile, due to their length,:
<img width="247" alt="screenshot 2018-03-02 13 02 29" src="https://user-images.githubusercontent.com/2288238/36879941-3a3a25ee-1e1a-11e8-97bf-14f238d97182.png">

**Comment by matthewberryman** [comment]
@LucieGueuning I did a fair amount of work on this today, Devika will be looking at the second bullet point (around check boxes plus display of types and subtypes) and other issues starting Monday.

**Comment by matthewberryman** [comment]
@LucieGueuning this is now in dev. Tomorrow my time I will be merging to prod.

**Comment by LucieGueuning** [comment]
Could you please add 'Details' to severity? Thanks. 

Then all good for merging

**Comment by matthewberryman** [comment]
@LucieGueuning ok, I have put that in and also changed "Scale" to "Severity scale:" for consistency.

**Comment by LucieGueuning** [comment]
Exact.

Lucie Gueuning
REACH Project Manager, Emergency Response Support Unit
Médecins Sans Frontières - Hong Kong | 無國界醫生(香港)
Phone: +44<tel:+852%206279%207636> 7423 392179
Email: lucie.gueuning@hongkong.msf.org<mailto:lucie.gueuning@hongkong.msf.org>
Skype: lucie.gueuning
_______________
Please visit MSF REACH Project Deployment<https://msfintl.sharepoint.com/sites/hk/projects/MSF-REACH/SitePages/Home.aspx>

On 14 Mar 2018, at 11:34 PM, Matthew Berryman <notifications@github.com<mailto:notifications@github.com>> wrote:


@LucieGueuning<https://github.com/luciegueuning> ok, I have put that in and also changed "Scale" to "Severity scale:" for consistency.

**Comment by LucieGueuning** [comment]
Perfect. 
For consistency, please do put 'Security details', **without capital letter**, to do the same than 'Severity details' and 'Severity scale'. Thanks!
