### ISSUE TITLE
Share button for event link and report link

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#300]
having the icons to share by opening the right platform with the link in the clipboard. 

(for part 2)

**Comment by matthewberryman** [comment]
This is done (I forgot to tag the commits with issue reference)

**Comment by LucieGueuning** [comment]
Could you please upload a screenshot for me to see? I can't see that on REACH right now.

**Comment by matthewberryman** [comment]
Sorry, I have generic copy links in for both now; I was just looking at issue title and had forgotten about social media share icons, I can add in platform sharing links tomorrow.

**Comment by LucieGueuning** [comment]
two things: 
- when pressing the mail button, it says: I've a link to share with you. But in the email, there is not link to the event. 
- When pressing the share button, we should have a message saying: 'the link is well copy in your clipboard, ready to share'

**Comment by matthewberryman** [comment]
I tested the email sharing button repeatedly but could not reproduce the issue - the correct link was placed in the body of the email (noting that it's in the body of the email not the subject line, so that mail clients should render it as a hyperlink). The only thing I can think of is that it's a timing issue caused by higher latency your end, so I made a tweak to the code to help work around that, and tested several times over an artificially slower network connection and couldn't reproduce that bug.

I've added an alert as requested.

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/40431365-311cfc32-5e9f-11e8-8d5c-996948cc44c6.png)

**Comment by matthewberryman** [comment]
* No consistent way (across mail clients) of specifying body as html and it should auto-convert to a clickable hyperlink in most (recipient) email clients anyway - this is the case for the mail clients I use and have tested this.
* A blank line before signature block should be added by your mail client (in fact all the bug reports I can see for outlook are that it's adding two lines not omitting one), and behaves correctly in my mail app; it's not something we can control.

**Comment by LucieGueuning** [comment]
when the 'email' icon has disappeared?

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/44516286-96458100-a6bc-11e8-9f8c-5b514fdcaeb9.png)

**Comment by matthewberryman** [comment]
@LucieGueuning It's still specified in the sharing code, it's just not showing any more due to the changes requested in https://github.com/MSFREACH/msf-reach/issues/559 which have altered the space available. 
Easy fix: if there's another share icon I can remove (?) then removing it will make enough space for the email icon to be shown.
More detailed fix: changing the column space (something @mehrdadgit can take a look at).

**Comment by LucieGueuning** [comment]
remove facebook and twitter icon as we will never publish that into public feed (I think).

**Comment by matthewberryman** [comment]
done
