### ISSUE TITLE
TSR layer (of RSS Feed° is not up to date on Landing page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#325]
On TSR, there is, for example, an disaster in Australia (North) but this is not on the map on landing page. 

TSR, should be as PDC and others up to date on landing page on REACH. 

Comment from Remi.

**Comment by matthewberryman** [comment]
Events in Australia won’t be displayed per https://github.com/MSFREACH/msf-reach/issues/243 since Australia is not part of Asia. If you’d like Australian events displayed then please comment on that issue and close this one.



On 17 Mar 2018, at 07:42, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


On TSR, there is, for example, an disaster in Australia (North) but this is not on the map on landing page.

TSR, should be as PDC and others up to date on landing page on REACH.

Comment from Remi.

**Comment by matthewberryman** [comment]
Now that I am at my computer: I checked and Darwin is /just/ in the Bounding Box I'm using for Asia `(lat> -12.5611 && lat < 82.5005 && lng > 19.6381 && lng < 180.0000)`, and I can see a PDC flood watch warning for Darwin. I did some digging on its current data (with the Asia BBox turned off) as it should have shown up at the time Remi reported, even though it's now outside of the region, and turns out lat and lon co-ordinates were in the wrong order.
