### ISSUE TITLE
Private/public contact based on Active Directory

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#332]
cf #57

**Comment by matthewberryman** [comment]
From @LucieGueuning 
* need to be able to share this contact with another specific MSF staff
* need to see which contacts is private and public (UI to be suggested by @anexact)
* need to be able to put the private contact to public and vice-versa

**Comment by matthewberryman** [comment]
At the moment the private ones are displayed on the map and table alongside the regular ones but only for the user to which they're private. UI ideas need to encompass how to see which are private and which are public and also how to change them, plus I welcome your feedback on the current way that users indicate private contacts on entry (tick box on start).

**Comment by matthewberryman** [comment]
(accidentally closed via keyword during merge)

@LucieGueuning I've done a huge amount of work to get thus far and have merged into prod so there's something ready for demo. There are some known issues / things to think about:
* I still welcome feedback on UI. For now it's in the contact modal. Note that you have to hit enter when you've entered an email, and it will be looked up in the AD system (I am assuming permissions are set up the same in the prod AD environment). Amongst other things, the drop-down selector for privacy yes/no could be replaced with a static no depending on next point.
* I have allowed private contacts to be set to public but not the other way. I can do this with a medium amount of work if required.
* I have not allowed on-sharing (i.e. if user A shares with B then B can't share with C). I can change this if required, for now I didn't want to make security assumptions without checking with you first.
* There are some odd bugs that crop up if you haven't actively used the rest of the system in a while (~10 mins) and then go to add a private contact or share a private contact.
* There's some work I need to do around unit testing, code commenting, and some refactoring - in particular I think it makes sense to move the MS Graph API wrapper to another path.

**Comment by LucieGueuning** [comment]
Great work. 

I am testing it right now with Natasha. A few points need to be improved (but as low priority): 
- We should share by entering the name of the people and not the email address (Picture 1)
- The system should suggest the profile of the people (Picture 2)
- I need to get an email to get notified that Natasha shared a contact with me

Picture 1: 
![image](https://user-images.githubusercontent.com/25951555/39225829-89e51c88-4846-11e8-857a-76486d701756.png)

Picture 2
![image](https://user-images.githubusercontent.com/25951555/39225873-d84ffbc2-4846-11e8-8b4e-a98cee3f048d.png)

**Comment by matthewberryman** [comment]
Quoting comment from @LucieGueuning  w/out confidential information:
Great work.

I am testing it right now with Natasha. A few points need to be improved (but as low priority):
* We should share by entering the name of the people and not the email address 
* The system should suggest the profile of the people
* I need to get an email to get notified that Natasha shared a contact with me

**Comment by matthewberryman** [comment]
@LucieGueuning to avoid "odd bugs that crop up if you haven't actively used the rest of the system in a while (~10 mins) and then go to add a private contact or share a private contact." aka #393 I've developed a partial workaround that I can rapidly deploy on demand before the demo tomorrow if required (https://github.com/MSFREACH/msf-reach/pull/394). This disables the checkbox on the first contact page to mark a contact as private as well as simply throwing an alert saying 'feature not supported yet' if any change to privacy is made / if an email address to share to is entered on the contact modal. These UI changes are to reflect in this demo branch I don't store the user ID (to avoid the bug requiring a refresh) and hence a contact cannot be made private. You're still able to demo the feature in the test environment.

**Comment by LucieGueuning** [comment]
From the excel sheet, all of them who are mentioned as contact of Natasha need to be under Natasha profile database on REACH.

**Comment by matthewberryman** [comment]
@LucieGueuning Just to update you with good news on this in hopefully straightforward English:

* The error messages that were showing up (per previous comment here and https://github.com/MSFREACH/msf-reach/issues/393 ) were because I was using version 1 of the Microsoft login system, which meant I had to complete the second half of the auth process with the Graph API (for looking up other user details) separately. To get and maintain long term tokens from that, to avoid the errors that show up after a short time, would have been a lot of work. Luckily swapping to version 2 of the MS login system pushes most of the logic of that back to Microsoft. But once I swapped and got the access token, I needed to temporarily add some logging to our server to watch the three-way dance and token passing between Microsoft, our server, and the web client, in order to understand how to pass it back in for auth with the Graph API, as part of a code rewrite to use version 2.

* I have tested it in our test environment and it all seems great but need to do some more testing tomorrow before I merge back to prod as there's one use case that takes an hour and a bit of waiting to test it.

* After that I will look at searching by name and email notification.

* I will raise a separate issue for import of Natasha's private contacts.

**Comment by LucieGueuning** [comment]
As per contract, we need to be satisfy with the feature before we close it.

As per email: Re. contact search, the user requires, in addition to the results shown on the map, the results shown on the table below the search function. Can it be like the same feature than on the event page: having the contacts on the map shown on table and synchronise based on the map zoom? 

Many thanks.

**Comment by matthewberryman** [comment]
@LucieGueuning the display of search contacts is:
1. Not related to this feature, as defined above.
2. Not in the contact.
3. Was specified in email after the requested deadline for issues to be filed on GitHub for the current milestone. 

I will open a new issue for this feature and assign to the next milestone.

**Comment by LucieGueuning** [comment]
I am testing this feature right now and :

- need to see which contacts is private and public (UI to be suggested by @anexact)
- I need to get an email to get notified that Natasha shared a contact with me

**Comment by LucieGueuning** [comment]
- need to be able to delete contact that I have input into the REACH platform

**Comment by matthewberryman** [comment]
* The contact modal already shows the current status private/public. Happy to re-open if there are any suggestions, but there's already limited space in the events page table for contact information.
* Email notification will be done soon - note this was broken off as separate issue https://github.com/MSFREACH/msf-reach/issues/399 and the rest of this is done.
* I've opened a new issue for operators deleting contacts https://github.com/MSFREACH/msf-reach/issues/409

**Comment by LucieGueuning** [comment]
- need to see on the small pop-up window on landing page when you click on specific contact if it is public/private
- ok well ntoed
- ok well noted

**Comment by LucieGueuning** [comment]
Please do not close issue if it is not complete (cf. first point: need to see on the small pop-up window on landing page when you click on specific contact if it is public/private)

**Comment by anexact** [comment]
The public/private setting does not need a pop-up. The design decisions for making this a successful platform cannot be made on a whim, or for the sake of tagging GitHub issues in a schedule—the clarity, coherence, and efficiency of the UX is being compromised by the false timeline / schedule of the Milestones and poor management of the product. This must be addressed as soon as possible as it will make the rest of the development increasingly frustrating if the decisions become a matter of timeline completion rather than thoughtful design!

**Comment by matthewberryman** [comment]
At any rate, this is done. @LucieGueuning can you please make sure you refresh your browser cache and check carefully before re-opening.
<img width="226" alt="screenshot 2018-05-22 05 08 14" src="https://user-images.githubusercontent.com/2288238/40325180-2d27e154-5d7e-11e8-9530-4812a3986f8a.png">

**Comment by LucieGueuning** [comment]
Thanks Matthew! All good!
