### ISSUE TITLE
clustering of contacts on landing page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#339]
On contact details, from Google form, sometimes. living home location is only the capital of one country. On REACH contact card, it allows to input only capital on the search box, then it display the red icon at the very same location than the previous one which was located at the same capital (New Delhi). How to avoid that? Should we suggest to have a slightly different GPS coordinates if there is already a contact located in New Delhi for example. 

Maybe linked to #287

**Comment by matthewberryman** [comment]
The approach to use is the clustering we use for health sites, and for contacts as displayed on the events page, where it pops up an icon showing the number at that location, and then if you click on that it shows all the contacts in a graphical arrangement around that point, rather than making the GPS co-ordinate data incorrect. 

Many of the contacts in #287 had addresses that Google either couldn't find (typos?) and in a number of cases they were missing street data and only had a country, in which case Google uses a default point (capital) for that country.

**Comment by matthewberryman** [comment]
@LucieGueuning It's not clear what you mean by https://github.com/MSFREACH/msf-reach/issues/354
I clustered close-by contacts as a red icon with the number of contacts at that location, that when you click on will split open the cluster to reveal individual contacts with some separation between them, in order to solve this issue. I can tweak the look and feel of those icons but removing them (if that's what you're suggesting in #354 ??) would mean that nearby contacts cannot be clicked on.
