### ISSUE TITLE
Icon not loaded for event popup on landing page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#352]
![image](https://user-images.githubusercontent.com/25951555/38311766-e14645fe-3817-11e8-98ca-17b96ba25f29.png)

**Comment by matthewberryman** [comment]
Just deploying a fix for better handling icons of natural disaster subtypes—that bit of code broke because we moved to having multiple types and subtypes. At the moment (with this fix) I only have an icon displayed for the first type / natural disaster sub_type (if natural disaster is one of the types). @LucieGueuning @anexact I need your feedback on whether we display
* /all/ icons for all types and subtypes, or
* no icon, or
* a generic event icon
to complete this fix.

**Comment by anexact** [comment]
@LucieGueuning can you comment on this? It was not clear from our meeting, but if still not clear, can you address on Tuesday in review with @matthewberryman?

**Comment by anexact** [comment]
@matthewberryman closed #360 sorry

**Comment by LucieGueuning** [comment]
we need to display specific icons for each types of event and sub-types of event (if any)
