### ISSUE TITLE
contact deletion by operator/viewer who entered it

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#409]
separate to contacts being able to delete ( https://github.com/MSFREACH/msf-reach/issues/227 )

**Comment by matthewberryman** [comment]
Also public ones per discussion with @LucieGueuning

**Comment by mehrdadgit** [comment]
Done together with #473 and in branch issues/473

**Comment by LucieGueuning** [comment]
public ones only able to be deleted by operators.

**Comment by matthewberryman** [comment]
Yes had communicated that to @mehrdadgit separately in discussions. I will review this code and merge into dev later today.

Sent from my iPhone

On 14 Nov 2018, at 05:44, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


public ones only able to be deleted by operators.

**Comment by LucieGueuning** [comment]
Great. Work perfectly. As mentioned in #432, having the red sentences before for viewers so that they won't try as they know they don't have the ability to do it; same for deletion of event. 

Either, having the red sentences at the top for every features, or the best won't be: to not have the red cross or the delete contact button if you are a viewer: 
![image](https://user-images.githubusercontent.com/25951555/48498807-ec930d80-e82e-11e8-9110-ad4510253b01.png)


Please advice on the best solution you are thinking of

**Comment by matthewberryman** [comment]
@mehrdadgit
We could just fiddle with css to hide the delete buttons based on the permissions check API I wrote for #432 (under /utils API).

Sent from my iPhone

On 15 Nov 2018, at 04:01, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


Great. Work perfectly. As mentioned in #432<https://github.com/MSFREACH/msf-reach/issues/432>, having the red sentences before for viewers so that they won't try as they know they don't have the ability to do it; same for deletion of event.

Either, having the red sentences at the top for every features, or the best won't be: to not have the red cross or the delete contact button if you are a viewer:
[image]<https://user-images.githubusercontent.com/25951555/48498807-ec930d80-e82e-11e8-9110-ad4510253b01.png>

Please advice on the best solution you are thinking of

**Comment by mehrdadgit** [comment]
Done @matthewberryman
