### ISSUE TITLE
When using my Mac, I can't scroll up and down the map layers menu. When I try to scroll in the area using my mouse pad, it just zooms the map in and out. 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#420]
![mac bug](https://user-images.githubusercontent.com/25951555/40357186-3f135b5c-5db3-11e8-86e4-22f5296c03aa.jpg)

**Comment by matthewberryman** [comment]
Fixed in leaflet except if using the grouped layer control plugin (which we are); in which case needs additional fix per https://github.com/Leaflet/Leaflet/issues/2882#issuecomment-117825234

Sent from my iPhone

On 22 May 2018, at 20:28, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


[mac bug]<https://user-images.githubusercontent.com/25951555/40357186-3f135b5c-5db3-11e8-86e4-22f5296c03aa.jpg>
