### ISSUE TITLE
Adding links on a per user basis

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#453]
Important feature to keep as such on GitHub. No duplication

**Comment by matthewberryman** [comment]
Per discussion on Skype:
1. We already support RSS feed selection (from the existing feeds) on a per user basis. I assume you mean around adding new RSS feeds.
2. Not every feed requested so far has been publicly accessible, nor have they all been RSS feeds - the TSR feed is just a web site that I have written separate code to parse as HTML (not RSS which is a dialect of XML) to extract the information from.
3. It's not that common to have geospatial information (in georss format), without which we can't map the data, thus we would have to put into a table only. This would require rework of the code and rethink of the UX as we have a close integration between map and table in terms of selection of RSS feeds and also zooming to item on map on selection in table etc.
4. There's been a lot of manual work (icon development and coding) customised to each RSS feed added so far to extract the information from the title, link, and summary information and use that in visually representing the information on the map for example some have disaster types, and additionally PDC has a status. 
5. Also applies to consistency of written representation in the table, too.

Particularly because of 3, but also supporting user preferences around RSS feeds and display, I am wondering why an RSS feed reader application and/or bookmarks bar cannot be used alongside REACH instead, e.g. as per following screenshot. To do this task would require writing a whole new full featured RSS feeder (that can save individual preferences, do scheduled polling rather than our on-demand "hack") etc.
<img width="1379" alt="screenshot 2018-05-31 13 38 40" src="https://user-images.githubusercontent.com/2288238/40760438-2a975fe2-64da-11e8-9f1c-932840ba3a56.png">

For reference, particularly on illustrating some of the above issues, tagging specific requests https://github.com/MSFREACH/msf-reach/issues/395 https://github.com/MSFREACH/msf-reach/issues/384 https://github.com/MSFREACH/msf-reach/issues/127 https://github.com/MSFREACH/msf-reach/issues/271

**Comment by matthewberryman** [comment]
Speaking with Remi; for other regions https://github.com/MSFREACH/msf-reach/issues/455 sounds like we do need to replicate /embed some RSS reader features within REACH at some point. So need to think about workload around database, UI and API changes on that front. And need to promote use of georss. https://github.com/MSFREACH/msf-reach/issues/417

**Comment by matthewberryman** [comment]
@anexact need your UX feedback on how we do this

**Comment by matthewberryman** [comment]
Embedding RSS (incl non-geospatial) within the system (database and UX) could allow AI to leverage this information alongside everything else.

**Comment by matthewberryman** [comment]
@mehrdadgit 
I've made a start on this in https://github.com/MSFREACH/msf-reach/commit/16e7a525ac6e69c6b23e34dc2fd69bec1c0a6d0d and corresponding schema change https://github.com/MSFREACH/msf-reach-schema/commit/6bbe1e1cedabed82d449abb3f1fe4532f568dd11
Todo: 
* In the modal, allow display of (data from API GET) and editing of markdown text, like with event notifications.
* Hyperlink named "open non-geospatial news links" at top of rss feed (probably another div, as exisiting div is IIRC overwritten by jquery), to open modal 
* Also reference the markdown cheatsheet @qclin added for notifications. I think best to refactor the help modal (html and also css) out.
* There's a model function for post but no /post yet in the bookmarks route index.js - please add. Note for get and post you'll need to fake the OID for now for local dev and test before I merge into issues/174 branch as deployed to test env.
* The /get method needs to be updated so that if the initial query as written returns zero rows, it should make another query for oid (uuid) consisting of all zeros, 00000000-0000-0000-0000-000000000000 , which is a default I will set per environment based on links from other issues.

**Comment by mehrdadgit** [comment]
@matthewberryman 
I do not understand what is the markdown field for ? Is this the name/title of RSS feed ? if so, why does it have to be in markdown format ?
Also if bookmarks table is going to store the custom RSS Feeds for the user, should we store the feed URL somewhere, in the same (or separate) table ?

**Comment by LucieGueuning** [comment]
Requirements for RSS feed: 
On landing page: 
- Users can choice their preferred RSS feeds based on a list already existing (at the first log in + a way to do even after to update the preferred list)
- Users can added RSS feeds if they are not yet 
- DISPLAY: Users can see their preferences on map and table (for the ones having geo info) + on pop-up showing by time updated with red dot as hyperlink (for the ones having none geo info)
 
On event page: 
- RSS feed shown on map and table are related to **type of event** and **location** (cf. Qiao and Paul work)

Does that make sense?

**Comment by LucieGueuning** [comment]
@matthewberryman 

Ok well noted. 

points 1 and 2 for Phase 2b
point 3 for Phase 2 extension
point 4 (event page): cover by Qiao and Paul UX/UI revamp package

**Comment by mehrdadgit** [comment]
should be ready for testing @matthewberryman

**Comment by matthewberryman** [comment]
@LucieGueuning ready for testing in the test environment (test.msf-reach.org) with starting default links per https://github.com/MSFREACH/msf-reach/issues/416 (note there seemed some overlap with ENSO links so I only added one to save a bit of space but can add others back in).

**Comment by LucieGueuning** [comment]
FEEDBACK: 
- Synchronised map and table for RSS feed geo-enable: 
![image](https://user-images.githubusercontent.com/25951555/47849661-6dcbb880-ddca-11e8-99c9-afa851296beb.png)
- ability to customised the same way the geo-enable one. SOL: Having a second balck button next to the first one with: 'Open geospatial news feeds'. And then possibility to remove, add or edit the link for geo-enable. It then sends a request to add it manually to the map or can it be automatic? 
**How can we have the customised RSS feed for geo spatial ones?** 
- Can we have a narrow to return back to edition, more user friendly. You don't want to close that window, you just want to go back to the previous one. 
![image](https://user-images.githubusercontent.com/25951555/47849628-4ffe5380-ddca-11e8-9c0f-21f326dc0a9a.png)
- ug in the edit pop-up display: 
![image](https://user-images.githubusercontent.com/25951555/47850145-28a88600-ddcc-11e8-98eb-687e2d1eae0c.png)

**Comment by LucieGueuning** [comment]
For the last comment: I know, imagine if the hyperlink is to keep and that long, it will be out of the box.

**Comment by mehrdadgit** [comment]
Gotcha

**Comment by mehrdadgit** [comment]
Go back button and long-hyperlink-bug fixed; note it is on #174 branch.

**Comment by LucieGueuning** [comment]
Thanks Mehrdad. This can go to prod, to be confirmed with Matthew

**Comment by matthewberryman** [comment]
Great, I will move to prod tomorrow (my time) - just a bit busy this afternoon and I need to make sure I get the database changes in correctly for this one.

**Comment by matthewberryman** [comment]
@mehrdadgit I'll also need to go through and cherry-pick your latest commit over to the issues/453 branch to merge just that (while work proceeds on issues/174 branch).
