### ISSUE TITLE
UI - quick feedback - auto-expand field on event page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#531]
On Event page, auto expand the items if there’s input. For example in this event, auto expand “Notification” and “External Capacity”.

**Comment by matthewberryman** [comment]
@qclin ah, I should have tested your work in issues/531 before merging. There's an issue here:
https://github.com/MSFREACH/msf-reach/blob/fc43fdf2ec544e5b6a07f195ef21a07c27c4c5e1/public/resources/js/events.js#L1529
in that `typeof null` actually returns 'object', and furthermore not all objects have a `.length`, and similarly at https://github.com/MSFREACH/msf-reach/blob/fc43fdf2ec544e5b6a07f195ef21a07c27c4c5e1/public/resources/js/events.js#L1531 
just because something isn't null doesn't mean it has a length. Off the top of my head you either want `typeof(x)==='string'` or `Array.isArray(x)` before calling length (an array has type 'object' but then so does a dict and dict's don't have a `.length`). Can you please fix this bit of code.
