### ISSUE TITLE
support multiple countries for events

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#534]
I will shortly add some initial support for this. I would like to have a map-based entry for regions i.e province/state (looks like this code was commented out with the change to Vue.js and we need to bring this back in @mehrdadgit ), and when that list is updated, the list of countries should also be updated if a new region.

I think it's best to allow operators to update this rather than having it automatically updated based on incoming reports as I had talked about with @LucieGueuning, as:
* A report may be spurious.
* An operator may want to flag a region / country for monitoring in anticipation of a report coming in.

**Comment by qclin** [comment]
if user enters Region, we’ll also append Country info like this 
`{country: “germany”, region: “berlin”} `

else if user only enter Country we will append only Country 
`{country: “germany”}`

wondering if country & region should be a binding object so 
if user remove Berlin from the Region, we also splice out Germany, since it was added together 
And user can add Germany back in on it’s own

will also filter duplicate countries, if frankfurt and berlin are both added, will only show Germany once.

if so, we should change the fields to have an AREAs array that supports objects

see https://github.com/MSFREACH/msf-reach/commit/52ab059a7e36f35e34d39484d13e40e5fdaada8f

**Comment by matthewberryman** [comment]
per email I think it's best to have an array of (region, country) tuples - for countries that have regions this will be present from Google autocomplete / Google geocoding (so you won't have only `{country: 'germany'}` and region will be bound to country as it's a tuple, but I'm not sure on region field from the Google API for countries that (don't really have) regions like Singapore - please check the Google API. 

Hence for splicing or display / other actions based on country if `{region: 'berlin', country: 'germany'}` and `{region: 'bavaria', country: 'germany'}` and `{region: 'new south wales', country: 'australia'}` then for display of countries you have two (Germany and Australia) and if you splice out the middle one then you still have those two countries (Germany and Australia).
