### ISSUE TITLE
How to edit meta-data - generic info on event page? 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#543]
for example, status or share point link?

**Comment by LucieGueuning** [comment]
FYI, for operational use, we need to change status to monitoring and need to add SharePoint link now created.

**Comment by matthewberryman** [comment]
For now, if not present as an in-line edit.
1. Click edit in new window.
2. Make changes.
3. Click "save edits"

In future, as part of #537 there will be an option to select the new status, and that will bring up a modal with fields to edit (incl. share point link) (so that particular one won't be fixed as part of this issue as already covered by #537).

The in-line editing can support more fields (aside from status but incl. sharepoint etc) 
@qclin do you want to take a look at extending @mehrdadgit 's work?
