### ISSUE TITLE
Ability to set status back from closed -> open

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#603]
it becomes mission history. I want to change status back to explo. I couldn't. Would you mind, manually, re-iterate this event back to 'explorations status' please? 

Status should be editable even once the project is closed. 

![image](https://user-images.githubusercontent.com/25951555/44415070-633da900-a567-11e8-865c-1d462b56516a.png)

**Comment by matthewberryman** [comment]
@LucieGueuning I have re-opened that particular event in the database.
@qclin Please work on functionality so that end users (with operator permissions - ref. other write-protected APIs) can re-open events; needs event status set to 'active' and also need to revert event.metadata.event_status as well.

**Comment by LucieGueuning** [comment]
You didn't re-open the flood and dam collapse. You re-opened the Flood in Cambodia which is also good. Please re-open the following one: 
![image](https://user-images.githubusercontent.com/25951555/44456099-a2b3d600-a5f7-11e8-8acc-4dbff7a0b7bc.png)

**Comment by LucieGueuning** [comment]
@matthewberryman Urgent as I would like to send out email with link to this specific event

**Comment by matthewberryman** [comment]
@LucieGueuning on it, will send you a whatsapp when ready.

**Comment by matthewberryman** [comment]
@LucieGueuning This is now fixed, my bad for getting confused earlier (I hadn't had enough coffee ;) - see whatsapp for more details.

**Comment by matthewberryman** [comment]
@LucieGueuning This was added in the code but it didn't deploy due to a build failure, now rectified, and this is now being deployed to dev.

**Comment by matthewberryman** [comment]
@qclin

**Comment by matthewberryman** [comment]
This got lost in some other changes and needs to be put back in.

**Comment by mehrdadgit** [comment]
Hi @matthewberryman @qclin 
With the current way of handling events and missions this is a bit tricky; so in order to this as properly as possible, some points to consider are as follows.

Current state:
*  when an event is updated (` PUT api/events/:id` ) if `req.body.status === 'inactive'` a _new mission_ is created  and the event metadata is copied to the mission properties. 
* This newly created mission does not keep track of the `id` of original event. So, despite the fact original event record is there, there is no way of knowing to which event a mission belongs. Also a mission might get edited by a user while the original event record stays the same/out-of-date.
* In my opinion, for handling re-opening of a mission, in terms of API, this has to be revised  so that we have consistency and a clear logic.

A couple of alternatives in handling this:

1. Get rid of missions table and define a mission as any event with status === 'inactive. 
2. Backfill the id of event when  creating a mission like a `event_id` field in properties or a brand new, non-json field. When the user wants to re open a mission: just change the status of the corresponding event then delete the current mission record from DB. (note the mission might have been edited but the original event record will not have the latest changes).
3. Keep DB structure as is and when you need to reopen a mission -> create a brand new event ( with a new `id`) based on the mission. (and to avoid duplicated records: delete the event record when is turned to mission and vice versa) 
 
(1) is my favourite option but I believe it would need require a lot of re-work in terms of currently stored missions in DB, front-end changes, etc ? (3) seems like a bit of extra-work as well ? (2) might be easiest at the expense of lost consistency to some extent...  

In any case, I suggest a separate endpoint possibly under `api/missions/reopen` to handle reopening of an event, and in terms of UI I suggest a separate button on missions modal rather than trying to capture the status-change of the mission.

Just suggestions and observations; hope that helps, and sorry for long message :)

**Comment by matthewberryman** [comment]
@mehrdadgit Thing is there are a lot of missions now in prod, and (2) tracking event_id is what I had in mind for this.

**Comment by matthewberryman** [comment]
But for (2), can we not copy JSON properties/metadata back over? That helps ensure consistency. Although if problematic it's not too huge an issue, as this is mostly for accidental closure so there shouldn't be too much of a gap.

**Comment by mehrdadgit** [comment]
ok @matthewberryman how do we deal with finding the event id of currently stored missions in DB ?

**Comment by matthewberryman** [comment]
@mehrdadgit I'm not worried about those (I can manually find and reopen and copy if necessary in those cases)

**Comment by mehrdadgit** [comment]
Done on issues/174 branch needs operator with write permission for testing.
